SPACESHIP_TIME_SHOW=true
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_RPROMPT_FIRST_PREFIX_SHOW=true

SPACESHIP_PROMPT_ORDER=(
	host
	dir
	git
	python
	venv
	rust
	haskell
	lua
	sudo
	char
	)

SPACESHIP_RPROMPT_ORDER=(
	time
	exec_time
	exit_code
	)

SPACESHIP_HOST_PREFIX=''
SPACESHIP_HOST_COLOR='#ffca0a'

SPACESHIP_DIR_COLOR='#e90020'
SPACESHIP_DIR_PREFIX=''
SPACESHIP_DIR_SUFFIX=' '

SPACESHIP_CHAR_SYMBOL=''
SPACESHIP_CHAR_SUFFIX='  '
SPACESHIP_CHAR_COLOR_SUCCESS='#e90020'
SPACESHIP_CHAR_COLOR_FAILURE='#00DFFF'
SPACESHIP_CHAR_SYMBOL_ROOT='󰦣'

SPACESHIP_PROMPT_DEFAULT_PREFIX=' '

SPACESHIP_TIME_FORMAT='[%*]'
SPACESHIP_TIME_PREFIX=''
SPACESHIP_TIME_SUFFIX=' '
SPACESHIP_TIME_COLOR='#694cff'


SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_PREFIX=''
SPACESHIP_EXEC_TIME_SUFFIX=' '
SPACESHIP_EXEC_TIME_COLOR='#ff3c63'
SPACESHIP_EXEC_TIME_ELAPSED=0
SPACESHIP_EXEC_TIME_PRECISION=4

SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL=''
SPACESHIP_EXIT_CODE_COLOR='#DFFF00'

SPACESHIP_GIT_BRANCH_COLOR='#ff3c63'
SPACESHIP_GIT_PREFIX=' '
SPACESHIP_GIT_STATUS_COLOR='#694cff'
SPACESHIP_GIT_STATUS_SUFFIX=' '

SPACESHIP_RUST_COLOR='#fb5814'
