plugin_dirs = [
    '/home/rw/.wine/drive_c/vst',
    '/home/rw/reaperfiles/vst',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-8.18 (Staging)'
yabridge_host_hash = -3455544459850266564
